base_url = "https://notes.a13i.dev"
title = "Andreas' Notes"
description = "Monthly learnings and discoveries related to frontend, the web, and software engineering in general"
default_language = "en"

[markdown]
smart_punctuation = true
